name: Test Plugin
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup barebones project
        run: |
          mkdir test_proj && cd test_proj
          composer init --name test/test --no-interaction --type=library --stability=dev
          composer config repositories.wpunit-helpers '{"type": "vcs", "url": "https://github.com/pantheon-systems/wpunit-helpers.git"}'
          composer config allow-plugins.pantheon-systems/wpunit-helpers true
          composer require --dev pantheon-systems/wpunit-helpers:dev-${{ github.head_ref }}
      - name: Validate that bin files were copied
        run: |
          cd ${{ github.workspace }}/test_proj
          test -d bin || (echo "❌ bin directory not found" >&2 && exit 1)
          test -f bin/install-wp-tests.sh || (echo "❌ bin/install-wp-tests.sh not found" >&2 && exit 1)
          test -f bin/install-local-tests.sh || (echo "❌ bin/install-local-tests.sh not found" >&2 && exit 1)
          test -f bin/phpunit-test.sh || (echo "❌ bin/phpunit-test.sh not found" >&2 && exit 1)
          test -f bin/helpers.sh || (echo "❌ bin/helpers.sh not found" >&2 && exit 1)
          echo "✅ All bin files found"
